language: node_js
node_js:
- 7.9.0
before_install:
- openssl aes-256-cbc -K $encrypted_da6098d38e23_key -iv $encrypted_da6098d38e23_iv
  -in .travis/id_rsa.enc -out id_rsa -d
- mv id_rsa ~/.ssh -f
- chmod 600 ~/.ssh/id_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp .travis/ssh_config ~/.ssh/config

after_script:
- scp -o StrictHostKeyChecking=no app.js root@39.108.164.254:~/../home
